### ISSUE TITLE
npm can't find react-flexgrid

### ISSUE THREAD

**Issue by 0x80** [andreypopp/react-flexgrid#1]
npm ERR! node v0.11.14
npm ERR! npm  v2.1.17
npm ERR! code E404

npm ERR! 404 Not Found: react-flexgrid
npm ERR! 404 
npm ERR! 404 'react-flexgrid' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by eliquious** [comment]
+1

**Comment by andreypopp** [comment]
Hi, I didn't publish it because it was experiment, which is failed in my opinion. Feel free to fork and publish it if you feel it can be useful.

**Comment by 0x80** [comment]
OK no problem, but maybe you could mention it on the page instead of the install instructions. I since moved to a different approach.

**Comment by ezmiller** [comment]
hi @andreypopp may i ask why the experiment failed. i'm developing a project in react using material-ui, which does not currently have a grid implementation. i came across your experiment here and it looked promising. 

there's another react-flexbox available via npm here: https://github.com/nkt/react-flexgrid

i'm in the process of trying to understand how to think about grids within a React implementation. so i'm curious to know what insights you gained from your experiment. if you are willing to share.
